### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'warning'

### ISSUE THREAD

**Issue by glimchb** [linux-nvme/nvme-stas#12]
on 
```
# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.5 (Ootpa)

# uname -r
5.16.7-1.el8.elrepo.x86_64
```

I see 
```
# /usr/bin/python3 -u /usr/sbin/stafd --syslog
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/staslib/stas.py", line 299, in __init__
    options = [ option.split('=')[0].strip() for option in f.readlines()[0].rstrip('\n').split(',') ]
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/sbin/stafd", line 91, in <module>
    from staslib import stas, avahi # pylint: disable=wrong-import-position
  File "/usr/lib64/python3.6/site-packages/staslib/stas.py", line 329, in <module>
    NVME_OPTIONS = NvmeOptions()
  File "/usr/lib64/python3.6/site-packages/staslib/stas.py", line 303, in __init__
    LOG.warning('Cannot determine which NVMe options the kernel supports')
AttributeError: 'NoneType' object has no attribute 'warning'
```

Root cause is here - import ordering...

see https://github.com/linux-nvme/nvme-stas/blob/main/stafd.py#L91
```
from staslib import stas, avahi # pylint: disable=wrong-import-position
```
which calls calls  https://github.com/linux-nvme/nvme-stas/blob/main/staslib/stas.py#L329
```
NVME_OPTIONS = NvmeOptions()
```
which can call LOG but log defined only later on here https://github.com/linux-nvme/nvme-stas/blob/main/stafd.py#L106

**Comment by martin-belanger** [comment]
Fixed by this pull request: https://github.com/linux-nvme/nvme-stas/pull/14
